# Generated by Django 5.1.2 on 2024-10-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='featuredimage',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
